baseurl = "https://santaidikit.online/"
languageCode = "id-id"
languageLang = "id"
title = "santaidikit.online"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
images = ["img/og-image.jpg"]
